title: "Portfolio de Iker Redondo Serra"
description: "Desarrollador web con enfoque en IA generativa. Proyectos ML/IA, demos interactivas y más."
baseurl: ""  # dejar vacío para user.github.io
url: "https://gameandnight.github.io"  # actualizar si se usa dominio personalizado

# Tema
remote_theme: "mmistakes/minimal-mistakes@4.24.0"

# Plugins soportados por GitHub Pages
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Información del autor
author:
  name: "Iker Redondo Serra"
  avatar: "/assets/images/avatar.jpg"  # si tienes una imagen de perfil aquí
  email: "iker.rs.1991@gmail.com"
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/gameandnight"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/tu-perfil"  # cámbialo por tu URL real
    - label: "YouTube"
      icon: "fab fa-youtube"
      url: "https://www.youtube.com/channel/ID_DEL_CANAL"  # cámbialo por el ID de tu canal

